In [2]:
# Add this at the top of your notebook
import sys
import os
sys.path.append(os.path.abspath('..'))  

# Now imports work
import pandas as pd
from src.sentiment import add_sentiment_to_df, aggregate_by_bank, aggregate_by_rating

### Sentiment Analysis

##### Load your cleaned data

In [3]:
# Load your cleaned data
df = pd.read_csv("../data/processed/reviews.csv")

print(f"Loaded {len(df)} reviews")
print(f"Columns: {df.columns.tolist()}")
df.head()

Loaded 1350 reviews
Columns: ['review_id', 'review', 'rating', 'date', 'bank', 'source']

,review_id,review,rating,date,bank,source
0,982b1262-3d54-4a12-811a-8b26b7ecc777,best app for financial sector,5,2026-05-14,CBE,Google Play
1,06f6640c-b65c-43e4-88ef-0a79be8b9534,it's a good application,5,2026-05-13,CBE,Google Play
2,eda74236-f7f3-4422-a139-a181e832bc27,thank you cbe,5,2026-05-13,CBE,Google Play
3,ff53332b-2e76-46d6-83d3-f93f968a4b18,is good,5,2026-05-13,CBE,Google Play
4,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13,CBE,Google Play

##### Add Sentiment Labels and score

In [5]:
# This one line does everything: loads model, classifies all reviews
df = add_sentiment_to_df(df)

print("Sentiment analysis complete!")
print("\nSentiment distribution:")
print(df['sentiment_label'].value_counts())

Sentiment analysis complete!

Sentiment distribution:
sentiment_label
positive    834
negative    468
neutral      48
Name: count, dtype: int64

In [6]:
df.head()

,review_id,review,rating,date,bank,source,sentiment_label,sentiment_score
0,982b1262-3d54-4a12-811a-8b26b7ecc777,best app for financial sector,5,2026-05-14,CBE,Google Play,positive,0.999166
1,06f6640c-b65c-43e4-88ef-0a79be8b9534,it's a good application,5,2026-05-13,CBE,Google Play,positive,0.999866
2,eda74236-f7f3-4422-a139-a181e832bc27,thank you cbe,5,2026-05-13,CBE,Google Play,positive,0.999756
3,ff53332b-2e76-46d6-83d3-f93f968a4b18,is good,5,2026-05-13,CBE,Google Play,positive,0.999839
4,363a5616-ed3d-4274-85ee-77071067f81d,wow,5,2026-05-13,CBE,Google Play,positive,0.999592

##### Aggregate sentiment scores

In [7]:
print("\nBy bank:")
print(aggregate_by_bank(df).round(1))

By bank:
sentiment_label  negative  neutral  positive
bank
BOA                  41.8      5.3      52.9
CBE                  29.1      2.9      68.0
Dashen               33.1      2.4      64.4

In [8]:
print("\nBy rating:")
for rating, results in aggregate_by_rating(df).items():
    print(f"\n{rating}★:")
    for sentiment, pct in results.items():
        print(f"  {sentiment}: {pct*100:.1f}%")

By rating:

1★:
  negative: 86.2%
  positive: 11.7%
  neutral: 2.1%

2★:
  negative: 80.0%
  positive: 17.5%
  neutral: 2.5%

3★:
  negative: 65.7%
  positive: 32.9%
  neutral: 1.4%

4★:
  positive: 52.0%
  negative: 43.1%
  neutral: 4.9%

5★:
  positive: 84.0%
  negative: 11.9%
  neutral: 4.1%